/* ==================================================================
   Düsseldorfer Stadtführer e.V. – Datengrundlage der Suche
   ------------------------------------------------------------------
   Diese Liste durchsucht das Suchfeld im Kopfbereich.

   EINE FÜHRUNG ERGÄNZEN ODER ÄNDERN:
   Einfach einen Block nach demselben Muster einfügen oder anpassen.

     titel  Name der Führung, so wie er angezeigt wird
     seite  Wohin der Treffer führt. Entweder eine eigene
            Detailseite ("nordpark.html") oder die Themenseite
            mit Sprungmarke ("stadtviertel.html#tour-volksgarten")
     thema  Überschrift der Gruppe – steht klein unter dem Treffer
     worte  Zusätzliche Suchbegriffe. Je mehr, desto besser
            wird die Führung gefunden. Sie werden nicht angezeigt.

   Auf Groß- und Kleinschreibung sowie auf Umlaute muss beim Suchen
   niemand achten – das erledigt js/script.js.

   Nach dem Bearbeiten: Komma am Ende jeder Zeile nicht vergessen,
   sonst lädt die Datei nicht.
================================================================== */

const TOUREN = [
  { titel: "Familien & besondere Bedürfnisse",
    seite: "besondere-beduerfnisse.html",
    thema: "Themenübersicht",
    worte: "Für Schulklassen, für Rollstuhlfahrer*innen und Menschen mit Seheinschränkung, für Neu-Düsseldorfer*innen aus aller Welt: diese Führungen sind auf besondere Bedürfnisse zugeschnitt",
    uebersicht: true },
  { titel: "Geschichte & Geschichten",
    seite: "geschichte-geschichten.html",
    thema: "Themenübersicht",
    worte: "Vom mittelalterlichen Dorf zur Landeshauptstadt, von starken Frauen über Düsseldorfer Originale bis zum Karneval: Wir erzählen die großen und die kleinen Geschichten hinter der Sta",
    uebersicht: true },
  { titel: "Kunst & Kultur",
    seite: "kunst-kultur.html",
    thema: "Themenübersicht",
    worte: "Düsseldorf ist eine Kunststadt – oberirdisch wie unterirdisch. Wir zeigen Ihnen, wo die Stadt kreativ wird: von U-Bahnhöfen als Kunstwerken über große Namen wie Joseph Beuys bis zu",
    uebersicht: true },
  { titel: "Sportlich",
    seite: "sportlich.html",
    thema: "Themenübersicht",
    worte: "Düsseldorf lässt sich auch in Bewegung entdecken: auf dem Rad, im Lauftempo oder zu Fuß mit sportlichem Anspruch – für alle, die Sightseeing und Sport verbinden möchten.",
    uebersicht: true },
  { titel: "Stadtviertel",
    seite: "stadtviertel.html",
    thema: "Themenübersicht",
    worte: "Düsseldorf ist keine Stadt, sondern viele. Zwischen Oberkassel und Gerresheim, zwischen Carlstadt und Nordpark liegen Welten – jede mit eigener Geschichte, eigenem Tempo, eigenem T",
    uebersicht: true },
  { titel: "Touren außerhalb von Düsseldorf",
    seite: "touren-ausserhalb.html",
    thema: "Themenübersicht",
    worte: "Vom Kölner Dom bis zum Drachenfels, von der Industriekultur im Ruhrgebiet bis zur Kunst auf der Museumsinsel Hombroich: Wir nehmen Sie mit auf Entdeckungen im Umland.",
    uebersicht: true },
  { titel: "(Kann man) Joseph Beuys verstehen",
    seite: "joseph-beuys.html",
    thema: "Kunst & Kultur",
    worte: "Aktionskunst • Kunstakademie • Vermächtnis Die Erinnerung an den Ausnahmekünstler Joseph Beuys prägt Düsseldorf." },
  { titel: "Advent, Advent – ein Bummel über die Weihnachtsmärkte",
    seite: "geschichte-geschichten.html#tour-advent-advent-ein-bummel-ueber-die",
    thema: "Glaube, Brauchtum und Feste",
    worte: "Weihnachtsmärkte • Adventszeit • Glühwein" },
  { titel: "Altbier & die längste Theke der Welt",
    seite: "altbier.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Hausbrauereien • Craft-Beer • Tradition Ein „bierernster“ Bummel durch charakteristische Straßen der Altstadt mit Besuch typischer Hausbrauereien." },
  { titel: "Altstadt",
    seite: "altstadt.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Rathaus • Burgplatz • Längste Theke der Welt Wie sich aus dem ehemaligen Fischerdorf eine moderne Metropole entwickelt hat." },
  { titel: "Altstadt und Japanviertel für Blinde und Sehbehinderte",
    seite: "besondere-beduerfnisse.html#tour-altstadt-und-japanviertel-fuer-blinde-und",
    thema: "Barrierefrei unterwegs",
    worte: "Ertasten • Erhören • Inklusiv" },
  { titel: "Architektur der Innenstadt (nicht nur neue Mitte)",
    seite: "geschichte-geschichten.html#tour-architektur-der-innenstadt-nicht-nur-neue",
    thema: "Von der Siedlung zur Metropole",
    worte: "Baustile • Fassaden • Stadtbild" },
  { titel: "Bahnhofsviertel",
    seite: "stadtviertel.html#tour-bahnhofsviertel",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Kunstwerke • Musik • Street-Art" },
  { titel: "Barrierefrei: Altstadt für Rollstuhlfahrer*innen",
    seite: "besondere-beduerfnisse.html#tour-barrierefrei-altstadt-fuer-rollstuhlfahrer",
    thema: "Barrierefrei unterwegs",
    worte: "Barrierefrei • Altstadt • Rollstuhlgerecht" },
  { titel: "Benrath",
    seite: "stadtviertel.html#tour-benrath",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Schloss • Gärten • Barock" },
  { titel: "Britischer Soldatenfriedhof Rheinberg",
    seite: "touren-ausserhalb.html#tour-britischer-soldatenfriedhof-rheinberg",
    thema: "Niederrhein",
    worte: "Gedenkstätte • Kriegsgräber • Geschichte" },
  { titel: "Bühne frei: Düsseldorf macht Theater",
    seite: "kunst-kultur.html#tour-buehne-frei-duesseldorf-macht-theater",
    thema: "Kunst & Kultur",
    worte: "Schauspielhaus • Bühnen • Kulturszene" },
  { titel: "Carlstadt",
    seite: "stadtviertel.html#tour-carlstadt",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Stadtpalais • Kultur • Markt" },
  { titel: "Das Beste von Düsseldorf",
    seite: "highlights.html",
    thema: "Von der Siedlung zur Metropole",
    worte: "Altstadt • Königsallee • Rheinturm Düsseldorf ist eine Stadt der kurzen Wege. Auf knapp 5 Kilometern zeigen wir die Höhepunkte der Stadt." },
  { titel: "Die Kirchen der Altstadt",
    seite: "geschichte-geschichten.html#tour-die-kirchen-der-altstadt",
    thema: "Glaube, Brauchtum und Feste",
    worte: "Sakralbauten • Altstadt • Geschichte" },
  { titel: "Die Skulpturen von Bert Gerresheim",
    seite: "kunst-kultur.html#tour-die-skulpturen-von-bert-gerresheim",
    thema: "Kunst & Kultur",
    worte: "Bildhauerei • Denkmäler • Stadtgeschichte" },
  { titel: "Die Säulenheiligen von Christoph Pöggeler",
    seite: "kunst-kultur.html#tour-die-saeulenheiligen-von-christoph-poeggeler",
    thema: "Kunst & Kultur",
    worte: "Altstadt • Fassaden • Steinfiguren" },
  { titel: "Dusseldorf for Expats",
    seite: "besondere-beduerfnisse.html#tour-dusseldorf-for-expats",
    thema: "Führungen für Expats",
    worte: "English • Newcomers • City Introduction" },
  { titel: "Düsseldorf divers – Vielfalt und Verfolgung (Diversity-Führung)",
    seite: "geschichte-geschichten.html#tour-duesseldorf-divers-vielfalt-und-verfolgung",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Vielfalt • Verfolgung • Erinnerungskultur" },
  { titel: "Düsseldorf für Schüler",
    seite: "besondere-beduerfnisse.html#tour-duesseldorf-fuer-schueler",
    thema: "Für Schulklassen und Kinder",
    worte: "Klassenausflug • Schulführung • Interaktiv" },
  { titel: "Düsseldorf kriminell (Altstadt und Kaiserswerth)",
    seite: "geschichte-geschichten.html#tour-duesseldorf-kriminell-altstadt-und",
    thema: "Natur, Fluss und dunkle Kapitel",
    worte: "Kriminalgeschichte • Altstadt • Kaiserswerth" },
  { titel: "Düsseldorf macht Landespolitik",
    seite: "geschichte-geschichten.html#tour-duesseldorf-macht-landespolitik",
    thema: "Politik, Macht und Geld",
    worte: "Landtag NRW • Politik • Macht" },
  { titel: "Düsseldorf pour Expats",
    seite: "besondere-beduerfnisse.html#tour-duesseldorf-pour-expats",
    thema: "Führungen für Expats",
    worte: "Français • Nouveaux arrivants • Découverte" },
  { titel: "Düsseldorf und die Welt – Düsseldorf international",
    seite: "geschichte-geschichten.html#tour-duesseldorf-und-die-welt-duesseldorf",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Partnerstädte • Migration • Weltoffenheit" },
  { titel: "Düsseldorfer Originale",
    seite: "originale.html",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Stadtgeschichten • Persönlichkeiten • Anekdoten Humorvolle Geschichten über die rheinische Lust am Leben und die Freude, dem Schicksal auch mal ein Schnippchen zu schlagen." },
  { titel: "Ehrenhof und Hofgarten",
    seite: "stadtviertel.html#tour-ehrenhof-und-hofgarten",
    thema: "Parks, Gärten und Friedhöfe",
    worte: "Museen • Tonhalle • Parkanlage" },
  { titel: "Essen",
    seite: "touren-ausserhalb.html#tour-essen",
    thema: "Ruhrgebiet",
    worte: "Zeche Zollverein • Industriekultur • Weltkulturerbe" },
  { titel: "Filmstadt Düsseldorf",
    seite: "filmstadt.html",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Hollywood • Drehorte • Oscar-Preisträger Klappe - Düsseldorf die Erste! Diese Stadt am Rhein ist ein veritabler Filmstar." },
  { titel: "Flingern",
    seite: "stadtviertel.html#tour-flingern",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Kreativ • Urban • Authentisch" },
  { titel: "Friedhof Golzheim",
    seite: "stadtviertel.html#tour-friedhof-golzheim",
    thema: "Parks, Gärten und Friedhöfe",
    worte: "Gartenkunst • Geschichte • Stille" },
  { titel: "Geldgeschichten und Wirtschaftsgeschichte",
    seite: "geschichte-geschichten.html#tour-geldgeschichten-und-wirtschaftsgeschichte",
    thema: "Politik, Macht und Geld",
    worte: "Handel • Banken • Wirtschaft" },
  { titel: "Gerresheim",
    seite: "stadtviertel.html#tour-gerresheim",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Basilika • Industrie-Erbe • Tradition" },
  { titel: "Golzheim",
    seite: "stadtviertel.html#tour-golzheim",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Künstler • Architektur" },
  { titel: "Grafenberg",
    seite: "stadtviertel.html#tour-grafenberg",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Industrie-Erbe • Eisenbahn • Wald" },
  { titel: "Heißes Pflaster: Wie sich Düsseldorf auf den Klimawandel einstellt",
    seite: "geschichte-geschichten.html#tour-heisses-pflaster-wie-sich-duesseldorf-auf-den",
    thema: "Natur, Fluss und dunkle Kapitel",
    worte: "Klimawandel • Stadtklima • Zukunft" },
  { titel: "In Düsseldorf spielt die Musik",
    seite: "kunst-kultur.html#tour-in-duesseldorf-spielt-die-musik",
    thema: "Kunst & Kultur",
    worte: "Tonhalle • Live-Musik • Konzerte" },
  { titel: "Japanisches Viertel",
    seite: "japanviertel.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Klein Tokio • Sushi + Ramen • Manga In Düsseldorf ist die drittgrößte japanische Gemeinde Europas zu Hause." },
  { titel: "Jüdisches Düsseldorf",
    seite: "geschichte-geschichten.html#tour-juedisches-duesseldorf",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Jüdisches Leben • Geschichte • Gedenken" },
  { titel: "Kaiserswerth",
    seite: "kaiserswerth.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Kaiserpfalz • Stiftsplatz • Diakonie Christianisierung des Rheinlands, Zoll, Treideln und Belagerung erzählen turbulente Geschichten, Kidnapping inklusive." },
  { titel: "Karneval und Brauchtum",
    seite: "geschichte-geschichten.html#tour-karneval-und-brauchtum",
    thema: "Glaube, Brauchtum und Feste",
    worte: "Karneval • Tradition • Brauchtum" },
  { titel: "Kinder suchen den verschwundenen Kurhut",
    seite: "besondere-beduerfnisse.html#tour-kinder-suchen-den-verschwundenen-kurhut",
    thema: "Für Schulklassen und Kinder",
    worte: "Mitmachführung • Rätsel • Für Kinder" },
  { titel: "Kloster Kamp",
    seite: "touren-ausserhalb.html#tour-kloster-kamp",
    thema: "Ruhrgebiet",
    worte: "Zisterzienser • Klostergarten • Terrassenanlage" },
  { titel: "Kulinarisches Düsseldorf",
    seite: "kulinarische-tour.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Altbier • Senf • Rheinische Küche Düsseldorfs „Nationalgetränk“ ist das Altbier." },
  { titel: "Kunst im Untergrund – die Wehrhahnlinie",
    seite: "wehrhahnlinie.html",
    thema: "Kunst & Kultur",
    worte: "U-Bahnkunst • Design • Untergrund Eine außergewöhnliche Kunstwelt öffnet sich unter der Stadt." },
  { titel: "Kunst im öffentlichen Raum",
    seite: "kunst-kultur.html#tour-kunst-im-oeffentlichen-raum",
    thema: "Kunst & Kultur",
    worte: "Skulpturen • Plätze • Entdeckungen" },
  { titel: "Kunst rund um den Nationalsozialismus",
    seite: "kunst-kultur.html#tour-kunst-rund-um-den-nationalsozialismus",
    thema: "Kunst & Kultur",
    worte: "Erinnerungskultur • Mahnmale • Geschichte" },
  { titel: "Köln",
    seite: "touren-ausserhalb.html#tour-koeln",
    thema: "Rheinaufwärts: Köln und der Drachenfels",
    worte: "Kölner Dom • Altstadt • Rheinmetropole" },
  { titel: "Köln versus Düsseldorf – ein amüsanter Schlagabtausch",
    seite: "geschichte-geschichten.html#tour-koeln-versus-duesseldorf-ein-amuesanter",
    thema: "Glaube, Brauchtum und Feste",
    worte: "Rivalität • Humor • Lokalpatriotismus" },
  { titel: "Königswinter + Drachenfels",
    seite: "touren-ausserhalb.html#tour-koenigswinter-drachenfels",
    thema: "Rheinaufwärts: Köln und der Drachenfels",
    worte: "Siebengebirge • Burgruine • Aussicht" },
  { titel: "Lebendiges Rathaus",
    seite: "lebendiges-rathaus.html",
    thema: "Politik, Macht und Geld",
    worte: "Rathaus • Verwaltung • Stadtgeschichte Dieser historische Spaziergang bringt Ihnen die Entwicklung der Düsseldorfer Stadtverwaltung näher." },
  { titel: "Links und rechts der Düssel",
    seite: "geschichte-geschichten.html#tour-links-und-rechts-der-duessel",
    thema: "Natur, Fluss und dunkle Kapitel",
    worte: "Fluss • Stadtgeschichte • Spaziergang" },
  { titel: "Literaten, Poeten und Dramatiker",
    seite: "kunst-kultur.html#tour-literaten-poeten-und-dramatiker",
    thema: "Kunst & Kultur",
    worte: "Heinrich Heine • Literaturmuseum • Wortkunst" },
  { titel: "Luxus und Glamour rund um die Kö",
    seite: "stadtviertel.html#tour-luxus-und-glamour-rund-um-die-koe",
    thema: "Rund um die Königsallee",
    worte: "Mode • Boulevard • Wasserlauf" },
  { titel: "Medienhafen",
    seite: "medienhafen.html",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Architektur • Wirtschaftsgeschichte • Wahrzeichen Wir schlagen einen Bogen von der Entstehung des Handelshafens um 1900 bis zum Eldorado der modernen Architektur und der Meile der Kreativen." },
  { titel: "Mittelalterliches Düsseldorf 1288: Wo man heute das Dorf findet",
    seite: "geschichte-geschichten.html#tour-mittelalterliches-duesseldorf-1288-wo-man",
    thema: "Von der Siedlung zur Metropole",
    worte: "Schlacht von Worringen • Stadtrechte • Mittelalter" },
  { titel: "Museumsinsel Hombroich",
    seite: "touren-ausserhalb.html#tour-museumsinsel-hombroich",
    thema: "Rund um Neuss",
    worte: "Kunst • Natur • Museumspavillons" },
  { titel: "Mülheim a. d. Ruhr",
    seite: "touren-ausserhalb.html#tour-muelheim-a-d-ruhr",
    thema: "Ruhrgebiet",
    worte: "Ruhrgebiet • Wasserbahnhof • Stadtgeschichte" },
  { titel: "Natur in der Stadt – Düsseldorfs grüne Seite",
    seite: "geschichte-geschichten.html#tour-natur-in-der-stadt-duesseldorfs-gruene-seite",
    thema: "Natur, Fluss und dunkle Kapitel",
    worte: "Stadtnatur • Grünflächen • Erholung" },
  { titel: "Natur: Düsseldorfer Natur, Fledermäuse, Vogelstimmen",
    seite: "geschichte-geschichten.html#tour-natur-duesseldorfer-natur-fledermaeuse",
    thema: "Natur, Fluss und dunkle Kapitel",
    worte: "Fledermäuse • Vogelstimmen • Naturkunde" },
  { titel: "Neue Mitte",
    seite: "neue-mitte.html",
    thema: "Von der Siedlung zur Metropole",
    worte: "Kö-Bogen • Architektur • Städtebau Rund um den Kö-Bogen ist mitten in der Stadt ein einzigartiges architektonisches und städtebauliches Ensemble entstanden." },
  { titel: "Neuss",
    seite: "touren-ausserhalb.html#tour-neuss",
    thema: "Rund um Neuss",
    worte: "Römerstadt • Quirinus-Münster • Rheinmetropole" },
  { titel: "Nordfriedhof",
    seite: "stadtviertel.html#tour-nordfriedhof",
    thema: "Parks, Gärten und Friedhöfe",
    worte: "Grabmale • Stadtgeschichte • Stille" },
  { titel: "Nordpark",
    seite: "nordpark.html",
    thema: "Parks, Gärten und Friedhöfe",
    worte: "Japanischer Garten • Aquazoo • Weite Der Düsseldorfer Nordpark hat eine bewegte Vergangenheit." },
  { titel: "Oberbilk",
    seite: "stadtviertel.html#tour-oberbilk",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Multikulturell • Stahlindustrie • Arbeiter" },
  { titel: "Oberkassel",
    seite: "stadtviertel.html#tour-oberkassel",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Jugendstil • Eleganz • Bohème" },
  { titel: "Pempelfort",
    seite: "stadtviertel.html#tour-pempelfort",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Kultur • Hofgarten • Cafés" },
  { titel: "Radtour",
    seite: "sportlich.html#tour-radtour",
    thema: "Sportlich",
    worte: "Fahrrad • Rheinufer • Aktiv" },
  { titel: "Sagen und Legenden",
    seite: "geschichte-geschichten.html#tour-sagen-und-legenden",
    thema: "Von der Siedlung zur Metropole",
    worte: "Mythen • Erzählungen • Volksglaube" },
  { titel: "Schloss Dyck",
    seite: "touren-ausserhalb.html#tour-schloss-dyck",
    thema: "Niederrhein",
    worte: "Wasserschloss • Park • Landschaftsgarten" },
  { titel: "Schloss Rheydt",
    seite: "touren-ausserhalb.html#tour-schloss-rheydt",
    thema: "Niederrhein",
    worte: "Renaissance • Mönchengladbach • Museum" },
  { titel: "Sight Running",
    seite: "sportlich.html#tour-sight-running",
    thema: "Sportlich",
    worte: "Laufen • Sightseeing • Fitness" },
  { titel: "Sight Walking",
    seite: "sportlich.html#tour-sight-walking",
    thema: "Sportlich",
    worte: "Zügiges Gehen • Sightseeing • Bewegung" },
  { titel: "Starke Frauen – Düsseldorfs weibliche Seite",
    seite: "geschichte-geschichten.html#tour-starke-frauen-duesseldorfs-weibliche-seite",
    thema: "Menschen, die Düsseldorf prägen",
    worte: "Frauengeschichte • Pionierinnen • Sichtbarkeit" },
  { titel: "Street-Art",
    seite: "street-art.html",
    thema: "Kunst & Kultur",
    worte: "Graffiti • Murals • Urbane Kunst Graffiti, Sticker, Paste-ups, urbane Installationen – so viel Kreativität findet sich an Hauswänden, Verkehrsschildern und Regenrinnen." },
  { titel: "Unterbilk",
    seite: "stadtviertel.html#tour-unterbilk",
    thema: "Düsseldorfs Stadtviertel",
    worte: "Szene • Lifestyle • Ex-Arbeiterviertel" },
  { titel: "Unterschätzte Kunstmeile Königsallee",
    seite: "stadtviertel.html#tour-unterschaetzte-kunstmeile-koenigsallee",
    thema: "Rund um die Königsallee",
    worte: "Skulpturen • Galerien • Architektur" },
  { titel: "Volksgarten",
    seite: "stadtviertel.html#tour-volksgarten",
    thema: "Parks, Gärten und Friedhöfe",
    worte: "Grün • Ruhe • Stadtgeschichte" },
  { titel: "Vom Dorf zur Stadt – Düsseldorfs Stadtentwicklung",
    seite: "geschichte-geschichten.html#tour-vom-dorf-zur-stadt-duesseldorfs",
    thema: "Von der Siedlung zur Metropole",
    worte: "Stadtgeschichte • Wachstum • Wandel" },
  { titel: "Zons",
    seite: "touren-ausserhalb.html#tour-zons",
    thema: "Rund um Neuss",
    worte: "Stadtmauer • Mittelalter • Rheinort" },
];
